### ISSUE TITLE
Adj Rule flipping between 9 plies draw and x moves 50mr

### ISSUE THREAD

**Issue by HansOveL** [coolchess123/tcec-gui#140]
Most of the time when 9 plies to draw is displayed in the Adj Rule field, only one of the engines have an eval within the draw range. This makes this field flip between 9 plies draw and x moves 50mr.
This could be avoided by never displaying 9 plies draw, instead just display only if there is less than 9 plies to draw (8 plies to draw, 7 plies to draw etc), as this is when both engines are within the draw range.

**Comment by arunsathya1309** [comment]
i quite dont understand, can u explain bit more, what is difference in 10 vs 9 draw

**Comment by HansOveL** [comment]
The idea was to display "x plies draw" in the Adj Rule box only if both engines agree on the draw, that is both of them are within the draw range (currently +- 0.05). One solution would be to check if they both are within draw range before displaying "x plies to draw". The other solution, would be to choose not to display "9 plies to draw", only display "8 plies to draw", "7 plies to draw", "6 plies to draw", "5 plies to draw", 4 plies to draw",  "3 plies to draw", "2 plies to draw", and "1 ply to draw", as in those 8 cases we know that both engines are within draw range.

I have never seen "10 plies to draw" been displayed.

**Comment by awbgithub** [comment]
I upvote this issue ... It is annoying when one engine has an eval outside the draw rule (> |0.05|) and the other doesn't ... and as a viewer I can't see how many plies to 50 mr when the display is showing the "9 plies to draw" - even though "plies to draw" is going to get reset after the next engine moves anyway.

The annoyance is exacerbated by the fact that in order for me to get the most size out of my chat window I have it set up so that I typically don't have the "plies to draw/50 mr" indicator in view unless I scroll - and by the time I scroll sometimes the other engine has already moved and instead of seeing the "50 mr" indicator the display is back to "9 plies to draw".

One thing to note is that if the solution mentioned in the OP for this issue is implemented, it could also resolve https://github.com/scs-ben/tcec-gui/issues/179 ... i.e. if the "50 mr" counter continues to display until **both** engines evals are within the draw rule (<= |0.05|) then it would obviate the need for a separate "50 mr" counter - which I think was the intention of combining the "plies to draw" counter with the "50 mr" counter in the first place?

**Comment by tcecspectator** [comment]
On the legacy GUI we had a separate window for 50mr with 50, draw, win - 50 showed moves to 50mr and draw, win showed moves to draw or adjudication.  On the new GUI we have one spot, Adj. Rule - so, sometimes we get conflict with the draw rule when one engine is within 0.08 and other is above 0.08.  The adj. Rule keeps switching back and forth between draw rule and 50mr.  Can't we separate out the 50mr to its own column in the header?

**Comment by coolchess123** [comment]
fixed
