### ISSUE TITLE
Larger names and logos

### ISSUE THREAD

**Issue by ASilver** [coolchess123/tcec-gui#95]
The display with the large evals is fine, but larger names and logos for the players would be nice.

**Comment by CatoTheYoungerTCEC** [comment]
Second that.

**Comment by xoto10** [comment]
Agreed. A related issue and possible improvement:

When viewing on a tablet (I use landscape mode), scrolling the page to the optimum position is important to get the most useful info on the screen. I need to see the board so I scroll until that is right at the top. But now the top of the middle part of the screen shows names and logos (not essential) and the right hand side (chat) is even worse, a big chunk of screen estate is taken up with the tabs, the "Stream Chat" and the cheering banner (if displayed). I can't fit much actual "chat" on the screen :-(

If the (e.g.) names were moved to above the board, the board would move down the page a bit helping the tablet view, and the logos could be made larger so that they include the space currently taken up by the names. Alternatively (perhaps better) the logos could be moved to be above the board.
